# -*- coding: utf-8 -*-
"""Project Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFEdCzMnp5jcZMmPtbGg9EANSjaYGP8r
"""

import pandas as pd

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")

print(dataset)

df1 = pd.DataFrame(dataset['by_polishing'])

df2 = pd.DataFrame(dataset['from_title'])

df3 = pd.DataFrame(dataset['from_title_and_content'])

df = pd.concat([df1, df2, df3], ignore_index=True)

print(df.info())

print(df.columns)

print(df.dtypes)

print(df)

print(df.head(10))

print(df.head(100))

print(df.columns)

Human_df = pd.DataFrame({'abstract': df['original_abstract'],'label': 'Human'})

AI_abstracts = pd.concat([
    df['allam_generated_abstract'],df['jais_generated_abstract'],df['llama_generated_abstract'],df['openai_generated_abstract']], ignore_index=True)
AI_df = pd.DataFrame({
    'abstract': AI_abstracts,'label': 'AI'})

combined_df = pd.concat([Human_df, AI_df], ignore_index=True)

print(combined_df['label'].value_counts())

print(df.duplicated(['original_abstract']).sum())
print(df.duplicated(['allam_generated_abstract']).sum())
print(df.duplicated(['jais_generated_abstract']).sum())
print(df.duplicated(['llama_generated_abstract']).sum())
print(df.duplicated(['openai_generated_abstract']).sum())

print(df.isnull().sum())

print(df.columns)

print(df.apply(lambda x: str(x).strip()))